### ISSUE TITLE
The special `.devcontainer/` directory is pretty powerful but isn't protected by `CODEOWNERS`

### ISSUE THREAD

**Issue by danswann** [comcode-org/.github#30]
### Problem
`.devcontainer/` contains configuration for Codespaces, including choosing a Docker image to base them on and running arbitrary commands every time one is created and/or started, but does not require review from @comcode-org/reviewers 

### Context
I think this is similar in power to things in the special `.github/` directory (e.g. running arbitrary commands in workflows), and I vaguely recall that being the reason we added `.github/` to `CODEOWNERS`. Should consider doing the same for `.devcontainer/`.

**Comment by seanmakesgames** [comment]
fixed in a handful of PRs
